### ISSUE TITLE
It's ok !

### ISSUE THREAD

**Issue by gege13007** [KieronQuinn/AmazfitStepNotify#2]
Sorry, finally I can now build & run your App on androidstudio ! And even I can run it !!!
The ways of AndroidStudio work in mysterious ways…

Could I ask to you what is the 'Test' & 'Android test' branches ???

Thanks.

**Comment by KieronQuinn** [comment]
They're auto generated, no need to worry about them.

**Comment by gege13007** [comment]
Thanks a lot !
I 've forgotten to say : I've no any Vibration on my Amazfit stratos. I've forced the Vibrate every time - Nothing happen. No error, no crash, but no Vibrate ...

**Comment by KieronQuinn** [comment]
Might be a defective device if none of the expected vibrations work
